export default {
  APP_INITIALIZED_SUCCESS: 'APP_INITIALIZED_SUCCESS',
  AUTH_CHANGE_LOGIN: 'AUTH_CHANGE_LOGIN',
  AUTH_CHANGE_LOGOUT: 'AUTH_CHANGE_LOGOUT',
  AUTH_LOGIN_START: 'AUTH_LOGIN_START',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
  AUTH_LOGOUT_START: 'AUTH_LOGOUT_START',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE',
  AUTH_SIGNUP_START: 'AUTH_SIGNUP_START',
  AUTH_SIGNUP_SUCCESS: 'AUTH_SIGNUP_SUCCESS',
  AUTH_SIGNUP_FAILURE: 'AUTH_SIGNUP_FAILURE',
};
