export default {
  APP_LOADING: 'APP_LOADING',
  AUTH_LOGGEDIN: 'AUTH_LOGGEDIN',
  AUTH_NOT_LOGGEDIN: 'AUTH_NOT_LOGGEDIN',
  AUTH_START: 'AUTH_START',
  AUTH_FAILURE: 'AUTH_FAILURE',
  AUTH_SIGNOUT_FAILURE: 'AUTH_SIGNOUT_FAILURE',
  DATA_LOADED: 'DATA_LOADED',
  LOADING: 'LOADING',
};
