export const rideSchema = [
  ['driver', 'integer 1 10'],
  ['totalSeats', 4],
  ['departTimestamp', 'timestamp 4 3'],
  ['postTimestamp', 'timestamp 0 3'],
  ['toLocation', 'location'],
  ['fromLocation', 'location'],
  ['passengers', 'passengers 0 4'],
  ['costPerSeat', 'integer 10 30'],
  ['description', 'placeholder'],
];

export const possibleValues = {
  passengers: [
    'caleb',
    'lukas',
    'tyler',
    'bob',
    'jack',
    'smith',
    'billy',
    'larry',
    'gorman',
    'rich',
  ],
  location: [
    'slo',
    'sf',
    'la',
    'fresno',
    'oakland',
    'palo alto',
    'san diego',
  ],
  placeholder: [
    'the',
    'i',
    'car',
    'very',
    'fast',
    'good',
    'enjoy',
    'thinking',
    'books',
    'stop',
    'read',
    'trump',
    'quick',
    'slow',
    'angry',
    'french',
  ],
};
